spring:
  application:
    name: customer-management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration  # Corrigido para o diretório padrão de migração
    baseline-on-migrate: true
    validate-on-migrate: false
